keys:
  - &admin age1lece5fgs54jycjjhclgtwvugrxuzajacd0mdsxna8v3sunj9tdsqfwdyyn
  - &macbook age1a49p4p9k0xwkwkh9e0t3zw88hwsuafs4t37nvfw3vtcq3kux0f0qavyd8r
  - &nixbox age1xnjsz6n9uzsmj3w5umdwv9scltt035rc8wne0u2hsh2zuafcdu2qhu5knn
  - &server age1zsv4uz44lkr0emz6u49jtwgg3svevm02e5xwgcp9fqwtw56vfv8qf60g8c

creation_rules:
  - path_regex: ^secrets/macbook/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *macbook
  - path_regex: ^secrets/nixbox/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *nixbox
  - path_regex: ^secrets/server/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *server
